.travis.yml
@fabiand 
Added deploy part to travis config, which creates a tarball with all templates/presets and uploads it to github releases.
https://trello.com/c/CURANTGC/26-8-presets-and-profiles-figure-out-upstream-build-and-test-procedures-for-presets
=> Travis-CI deploy github releases

templates/_linux.yaml
This fixes an issue Xenia found where the generated name was rejected by minishift:
```
/opt/minishift/oc process --local -f dist/templates/fedora-generic-tiny.yaml PVCNAME=mydisk | kubectl apply -f -
The VirtualMachine "fedora-Nlxy4wkUcsIjcwR6" is invalid: metadata.name: Invalid value: "fedora-Nlxy4wkUcsIjcwR6": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
=> Generated name must be all lowercase

templates/_linux.yaml
Add ioThreads feature in the Linux template generator.
By default uses **shared** ioThread policy.  But adds it as editable parameter. 
Current templates uses 2 cores maximum. It's a reason why I choose **shared** ioThread policy.
If user edit .spec.template.spec.domain.cpu.cores, then it can have a wish to edit ioThread policy to. 
So, user has this option.
In this time CNV supports only two policies - _shared_ and _auto_.
=> add iothreads feature

.travis.yml, automation/x-limit-ram-size.sh, makefile
add other sizes of templates to tests. Due to travis restrictions, large templates have to be updated to use only 6GB of RAM.
=> add other templates to test

.travis.yml, makefile
Failing of travis builds is probably caused by old version of kubevirt. This PR changes version to 0.10.0.
Added check which waits until vm is deleted.
=> fix failing travis build

generate-templates.yaml
This patchs turns off ansible gather_facts, because it fails stdci test
=> turn off ansible gather_facts

lookup_plugins/osinfo.py
Short integers are gone in Python 3 and long has become int.
Use `from builtins import int` to check for long and int on Python 2.
Signed-off-by: Ondra Machacek <omachace@redhat.com>
=> Make osinfo lookup plugin Python 3 compatible

templates/VALIDATION.md
In this patch:
1. minor fixes for consistency with JSONPath spec:
https://goessner.net/articles/JsonPath/index.html
2. clarify the missin "regex" argument
3. require notation to disambiguate JSONPath from strings
Signed-off-by: Francesco Romani <fromani@redhat.com>
=> doc: validation: add clarifications, close gaps

.travis.yml, automation/test.sh, generate-templates.yaml, templates/_linux.yaml, templates/win2k12r2.tpl.yaml
This PR adds desktop type for rhel, centos, windows os.
Desktop type templates (rhel, centos) and fedora, ubuntu will contains table devices
=> add desktop type for rhel, centos, windows os

automation/check-patch.rhel8.packages, automation/check-patch.windows2016.packages, automation/test.sh, lookup_plugins/osinfo.py, templates/_linux.yaml, templates/win2k12r2.tpl.yaml
This patch is an example of how to add validations that are based on libosinfo data. So far only the minimal memory requirements are checked.
Updated version of osinfo-db
=> Add required memory validation rules (and update the osinfodb)

.gitmodules, automation/test-rhel.sh, automation/test-windows.sh, automation/test.sh
move from outdated kubevirt scripts to the new project kubevirtci
This is needed for another, later PR, to be able to enable modern hyperv features.
=> Update kubevirt ci

automation/test-windows.sh
With the newly introduced feature (default masquerade instead of bridge) the check in the Windows stdci test is no longer valid (the Pod has a different IP than the VM). This patch updates the check to only count the number of occurences of "IPv4 Address" using the "ipconfig /all" command. This should be enough test to make sure the VM is running.
=> Fix stdci windows test when masquerade is used

makefile, templates/fedora.tpl.yaml
update Fedora image links
upgrade from Fedora 28 to Fedora 30
Link to previous fedora 28 is broken, new link contains Fedora 30.
=> FIX travis Fedora, Centos 8 tests

templates/_linux.yaml, templates/win2k12r2.tpl.yaml
In this PR we changed the default binding method
from _bridge_ to _masquerade_ in the template VMs.
Because live migartion is blocked when binding with _bridge_  on pod network (reasons for that are detailed here : https://github.com/kubevirt/kubevirt/issues/1633),
and because further issues might popup due to the IP delegation   from the hosting pod to the VM 
(more detailes here :  https://github.com/kubevirt/kubevirt/pull/2493),
we would like our template VMs to bind with the more preferable _masquerade_ binding method.
=> change default interface to masquerade instead of bridge

makefile
add -f option to curl when downloading images in tests
remove dead code (downloading of rhel images)
When image does not exists, test should fail immediately.
=> add -f option to curl when downloading images in tests

generate-templates.yaml
Just a refresh to reflect the list of currently supported guest operating systems.
=> Add Fedora 29, Fedora 30 and RHEL 7.7 to the list of guest OSes

templates/win2k12r2.tpl.yaml
This should fix https://bugzilla.redhat.com/show_bug.cgi?id=1769692 I hope.
=> Add kubevirt domain label to Windows VMs to fix virtctl expose

automation/connect_to_rhel_console.exp, automation/test-rhel.sh
remove unnecessary commands from connect_to_rhel_console.exp file
=> Remove unnecessary commands from connect_to_rhel_console.exp file

templates/_linux.yaml
this PR changes the template VM to be with
networkInterfaceMultiqueue, in order
to receive better network performances. 
benefits and reasoning behind networkInterfaceMultiqueue 
can be found here: 
https://www.linux-kvm.org/page/Multiqueue#Multiqueue_virtio-net
this PR requires kubevirt version 0.22.0  due to a bug fix included in this version
(https://github.com/kubevirt/kubevirt/pull/2783)
=> Use networkInterfaceMultiqueue: true

LICENSE, README.md
make it explicit the license on which the templates are released
Fixes: https://github.com/kubevirt/common-templates/issues/80
Signed-off-by: Francesco Romani <fromani@redhat.com>
=> license: add APACHE 2 license

templates/README.md, templates/_linux.yaml, templates/centos6.tpl.yaml, templates/centos7.tpl.yaml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/rhel6.tpl.yaml, templates/rhel7.tpl.yaml, templates/ubuntu.tpl.yaml, templates/win2k12r2.tpl.yaml
The release tag is kept it the labels for template itself
and in the VM object the template describes. There is
no change there.
Adding the version tag to the template name was a mistake
that will break upgrades. The name should never change.
When an incompatible change is needed, a copy of a template
should be created, given new name and edited as needed.
The original must stay backwards compatible forever!
=> Remove template release tag from template name

templates/centos6.tpl.yaml, templates/centos7.tpl.yaml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/rhel6.tpl.yaml, templates/rhel7.tpl.yaml, templates/ubuntu.tpl.yaml, templates/win2k12r2.tpl.yaml
This is a slight update to the recent patch that removed release
specific suffixes from template names. That fix forgot to take
into account the existing deployments that were done using SSP
operator and HCO.
The last version released via those channels was -v0.7.0 and
so to make upgrades from that release possible, I am readding
the suffix statically.
This can be interpreted as a version in which the template was
first officially released.
v0.7.0 is also the first version that appeared in a product
that supports upgrades. All versions prior that were always
static and had no upgrade guarantees.
Signed-off-by: Martin Sivak <msivak@redhat.com>
=> Add fixed version suffix -v0.7.0 to all templates

generate-templates.yaml, lookup_plugins/osinfo.py, test_plugins/eol.py
This patch should lower the maintenance burden when releases
of operating systems are added or deprecated. The new test
plugin osinfo_active checks the release dates and returns
True when the OS is currently active.
- RHEL and CentOS automatically expose all minor releases
- Fedora automatically exposes all releases that are or were
active during the past 6 months
Signed-off-by: Martin Sivak <msivak@redhat.com>
=> Load guest OS versions from osinfo-db automatically

templates/_linux.yaml
Linux templates have unnecessary trailing comma in validation
which causes error. This PR removes it.
//cc @fromanirh, @petrkotas 
=> remove unnecessary trailing comma from validation

automation/test.sh
This patch should fix the way, how images are downloaded and stored
in prow jobs. Previously, all images were stored in the same folder
under same name. It caused issues. This patch stores each image to its own folder. With this approach each job will have its own folder with image and
it prevents replacing image across jobs.
=> fix image downloading in prow tests

generate-templates.yaml
There is a discrepancy between common-templates RAM requests for VMs vs. the required RAM which is being validated against osinfo-db.
This PR rectifies the templates memory requests to use the same units as the osinfo-db.
Reference:
https://bugzilla.redhat.com/show_bug.cgi?id=1781815
=> Update Templates Memory Requests to Power-2-Based Values

.travis.yml, automation/test-windows.sh, automation/test.sh
changed size of os-3.11 cluster
changed win 2019 image name
disable rtc timer for win 2019 test. 
These changes are needed, because win 2019 have higher claims.
=> increased PV size and timeout for windows test

automation/test-rhel.sh, generate-templates.yaml
Removed tiny RHEL8 template as it does not comply with the minimal memory requirements
=> Removed tiny RHEL8 template 

automation/test-rhel.sh, generate-templates.yaml
This PR reverts #129. Templates cannot be deleted, because of backward compatibility (https://github.com/kubevirt/common-templates/blob/master/templates/README.md#template-edits).
=> Revert #129

generate-templates.yaml
Latest osinfo-db increased minimum required memory for rhel 8.
This PR increases minimum memory to 1.5Gi for rhel 8 tiny templates
=> increased minimum required memory for tiny rhel 8 template

automation/test-windows.sh, generate-templates.yaml, templates/windows.tpl.yaml
remove win 10 label from windows template (there is separate win10 template)
remove desktop workload from windows template (windows template
contains only server editions)
=> remove win 10 label from windows template

templates/windows.tpl.yaml
Previous PR (https://github.com/kubevirt/common-templates/pull/136) removed only annotation
=> remove win-10 label from windows server template

.gitignore, .travis.yml, automation/test-rhel.sh, automation/test.sh, versionsrc
This change is needed, because travis tests are running on os-3.11.0 which doesn't
support kubevirt v0.28.0. We need to migrate tests to OCP/OKD 4.*
=> hardcode kubevirt version to v0.27.0

templates/centos6.tpl.yaml, templates/centos7.tpl.yaml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/rhel6.tpl.yaml, templates/rhel7.tpl.yaml, templates/ubuntu.tpl.yaml, templates/win2k12r2-deprecated.tpl.yaml, templates/windows.tpl.yaml, templates/windows10.tpl.yaml
To instantiate a VM template, the user would have
to provide the name of PVC with the VM's disk.
Without it the template would not work.
This patch hides the VM templates from the catalog,
so users will not be confused.
=> Hide VM templates from the developer catalog

templates/_linux.yaml
For UI purposes this PR changes name.os.template.kubevirt.io annotation to be in format: name.os.template.kubevirt.io/<os_short_name>: <os_nice_name> or higher VM
=> change name.os.template.kubevirt.io annotation

templates/_linux.yaml
For UI purposes, remove the 'VM' postfix from linux operating systems names as it doesn't look good on the dropdown list in the new VM wizard:
Signed-off-by: Ido Rosenzwig <irosenzw@redhat.com>
=> Remove 'VM' postfix from linux operating systems

.travis.yml
In Travis, some of the python packages used were installed through apt,
others were from the virtenv.
Travis docs suggest against this: https://docs.travis-ci.com/user/languages/python/#travis-ci-uses-isolated-virtualenvs
This is an attempt to improve the situation.
Signed-off-by: borod108 <bodnopoz@redhat.com>
=> Use python packages from virtenv

generate-templates.yaml
updated requested memory for centos8 desktop/server and ubuntu tiny template
By updating osinfo-db minimal requirements increased for centos8 and ubuntu.
Template validator will then refuse to create tiny vm due to wrong requested memory. This PR increases requested memory for centos to 1.5Gi and 2Gi for ubuntu tiny template.
=> updated requested memory for centos8 desktop/server and ubuntu tiny template

generate-templates.yaml, templates/ubuntu.tpl.yaml
When creating a VM using the VM Wizard in the OpenShift Web Console,
if a user choose "Ubuntu 18.04 LTS", template forces Conroe CPU model.
This result in VM being unschedulable if this CPU type is not used
in the cluster.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1837670
=> remove conroe cpu model from ubuntu template

.travis.yml, travis_ci/test_syntax.sh, travis_ci/validate-min-memory-consistency.py
Currently the minimum memory requirements set in the "validation" part of the generated template
might actually be smaller than the requirements of newest minor version of the os,
this script will through an error for such a template.
IMHO a better solution should be implemented in the future, but the obvious one - setting the
minimal memory requirement to the actual OS requirement will not do since we need to keep naming consistency,
i.e. "tiny" template means a specific memory requirement throughout the system.
=> Add check for min memory consistency in generated templates

templates/_linux.yaml, templates/centos6.tpl.yaml, templates/centos7.tpl.yaml, templates/centos8.tpl.yaml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/rhel6.tpl.yaml, templates/rhel7.tpl.yaml, templates/rhel8.tpl.yaml, templates/ubuntu.tpl.yaml, templates/win2k12r2-deprecated.tpl.yaml, templates/windows.tpl.yaml, templates/windows10.tpl.yaml
Template version is now defined in a variable in the template file in order to include the template version in `objects.metadata.labels["vm.kubevirt.io/template"]` and allow template validator to find the template.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1816518
=> Align processed VM's 'vm.kubevirt.io/template' label with template's name (include the tempalte's version)

templates/win2k12r2-deprecated.tpl.yaml, templates/windows.tpl.yaml, templates/windows10.tpl.yaml
added bus attribute to windows cdrom validation rule
This change is needed, because disk definition contains CDRom and Disk in
the same structure (see here: https://github.com/kubevirt/kubevirt/blob/b8543ba8217a93be3cd0537442e7ff16c4979c5a/staging/src/kubevirt.io/client-go/api/v1/schema.go#L427). If template contains Disk, CDRom path (.spec.template.spec.domain.devices.disks[*].cdrom)
will be presented as well. And jsonpath will then throw an error, because cdrom path exists in the structure.
=> added bus attribute to windows cdrom validation rule

templates/win2k12r2-deprecated.tpl.yaml, templates/windows.tpl.yaml, templates/windows10.tpl.yaml
The validation rules for disks should only be executed
if thre are some disks.
=> Ignore disk validation if there are no disks

templates/LABELS.md, templates/win2k12r2-deprecated.tpl.yaml, templates/windows.tpl.yaml
this OS is no longer supported
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1860817
//cc @omeryahud 
=> remove windows 2008 labels from windows templates

automation/test.sh, templates/README.md, templates/_linux.yaml, templates/centos6.tpl.yaml, templates/centos7.tpl.yaml, templates/centos8.tpl.yaml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/rhel6.tpl.yaml, templates/rhel7.tpl.yaml, templates/rhel8.tpl.yaml, templates/ubuntu.tpl.yaml, templates/win2k12r2-deprecated.tpl.yaml, templates/windows.tpl.yaml, templates/windows10.tpl.yaml, travis_ci/test.sh
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1861297
//cc @omeryahud, @rmohr 
**Release Note**:
```release-note
Increase terminationGracePeriodSeconds to allow guest VMs to safely shutdown before deleting the VMI pod
```
=> increase terminationGracePeriodSeconds to 30 seconds

templates/win2k12r2-deprecated.tpl.yaml
Fixed BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1856412
Removed the labels used to query for templates from the deprecated windows template.
If the labels are removed, the template will not show up when consumers look for a template to use for a new VM,
but, because it (the template) still exists, template validator can find it in order to use it for validation of old VMs.
Release note:
```release-note
Removed the flavor/size labels from deprecated templates so they will no longer show up when querying for templates
```
=> Removed flavor/size labels from the deprecated windows template

templates/_linux.yaml, templates/windows.tpl.yaml, templates/windows10.tpl.yaml
add new SRC_PVC_NAME and SRC_PVC_NAMESPACE params to all templates.
These new params are added to unblock UI. They are not used in common templates
yet. In the future they will be used for datavolume template.
```release-note
add new SRC_PVC_NAME and SRC_PVC_NAMESPACE params to all templates.
```
=> add new SRCPVCNAME and SRCPVCNAMESPACE params 

templates/VALIDATION.md
```release-note
Updated the documentation to include a non-intuitive behavior of "valid" field.
```
=> Update validation documentation

.travis.yml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/ubuntu.tpl.yaml
**What this PR does**:
Minor fixes in the descriptions of Linux templates. Fedora disk image URL points to latest 32 version.
Updated osinfo-db, which adds EoL time to Silverblue 30 and removes if from annotations.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1852734
```release-note
- Changed Fedora disk image URL to the latest 32 release.
- Updated osinfo-db, so Silverblue 30 annotation is removed.
```
=> Fix descriptions and update osinfo-db

generate-templates.yaml, templates/_linux.yaml
Signed-off-by: Vatsal Parekh <vparekh@redhat.com>
Adding the default user to the cloud-init gives an easy way to check it
Fixes # [BZ1879483](https://bugzilla.redhat.com/show_bug.cgi?id=1879483)
```release-note
Add default cloud users to cloud-init
```
=> Add default cloud users to cloud-init

templates/VALIDATION.md, templates/win2k12r2-deprecated.tpl.yaml, templates/windows.tpl.yaml, templates/windows10.tpl.yaml
The "valid" JSON path has to point to the "bus" field,
because "disk" field always exists, even if it is "nil".
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1883468
```release-note
Fix validation rules for disk bus.
```
=> Fix validation for disks

templates/LABELS.md, templates/win2k12r2-deprecated.tpl.yaml, travis_ci/validate-min-memory-consistency.py
Removed OS labels and annotations from the deprecated windows template in order to hide it from consumers
To prevent creation of new VMs from deprecated templates
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=1881458
https://bugzilla.redhat.com/show_bug.cgi?id=1856412
```release-note
NONE
```
@rnetser @jelkosz @yaacov
=> Removed all OS labels from deprecated template

automation/test.sh
move secret creation after kubevirt is deployed
=> remove command which creates kubevirt namespace

travis_ci/test.sh
Updated the fedora image since travis cannot download the old one (gets 404) for an unknown reason
```release-note
Fedora image was updated to 32 in CI
```
=> Updated the fedora image

templates/windows10.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml
This is the test to see, if our new CI can handle hyper-v  (previously Francesco tried it https://github.com/kubevirt/common-templates/pull/70)
enable Hyper-V flags vpindex, synic, synictimer, tlbflush, frequencies, reenlightenment, ipi
Other hyper-v flags are not allowed:
evmcs: depends on KVM capability (currently vm with this flag will not run)
stimer: disabled in kubevirt
```
Enable Hyper-V flags (vpindex, synic, synictimer, tlbflush, frequencies, reenlightenment, ipi)
```
=> enable Hyper-V flags

automation/test_defaults.sh, automation/test_duplicate_templates.sh, automation/unit-tests.sh, templates/deprecated-windows.tpl.yaml, templates/win2k12r2-deprecated.tpl.yaml
Locked the version of the deprecated templates so they do not show up in the UI when the latest version is queried for
During an upgrade from previous template versions, the deprecated templates do not lose their labels (because the operator cannot remove those labels), so in order to exclude them from the UI view, I have locked their version to an older version, so they do not show up when the UI queries for the latest templates version
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1899460
```release-note
NONE
```
=> [Bugfix] Locked the version of the deprecated templates

templates/deprecated-windows.tpl.yaml, templates/win2k12r2-deprecated.tpl.yaml
Lock deprecated versions in the UI when the latest version is queried for
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1899460
Fixes #
```release-note
None
```
=> [release-v0.12] [Bugfix] Lock deprecated versions

templates/_linux.yaml, templates/windows10.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml
The os, workload and flavor annotations are added to VirtualMachines in
order to expose them in the kubevirt_vmi_phase_count metric.
Signed-off-by: Yuval Turgeman <yturgema@redhat.com>
Fixes #
```release-note
Add os, workload and flavor annotations to VirtualMachine
```
=> Add annotations for VirtualMachines

templates/centos6.tpl.yaml, templates/rhel6.tpl.yaml
rhel6 does not support the virtio interface model, which is kubevirt's
default. This change sets the interface model to rtl8139 explicitly on
rhel6, which is known to work there. It drops networkInterfaceMultiqueue
as it has no virtio device to apply on.
Bug-URL: https://bugzilla.redhat.com/show_bug.cgi?id=1794243
Signed-off-by: Dan Kenigsberg <danken@redhat.com>
```release-note
VMs created based on the rhel6 or centos6 templates can communicate over the pod network with no need to select non-virtio model.
```
=> use rtl8139 interface model on rhel6 and centos6

templates/centos6.tpl.yaml, templates/rhel6.tpl.yaml
e1000e is supposed to be faster. More importantly it is available in the
KubeVirt console, and reported to work just as well with rhel6 in
https://bugzilla.redhat.com/show_bug.cgi?id=1794243#c8
Signed-off-by: Dan Kenigsberg <danken@redhat.com>
```release-note
Use `e1000e` interface model on RHEL6 to conform with OpenShift console available models
```
=> rhel6: use e1000e instead of rtl8139

templates/README.md
Explain why Windows grace period is so long
commit 7127e2fd0 has set terminationGracePeriodSeconds for Windows
template on 3600 seconds, or one whole hour. I find it way too long, so
document the reason behind it. 
Signed-off-by: Dan Kenigsberg <danken@redhat.com>
```release-note
NONE
```
=> Explain why Windows grace period is so long

templates/centos6.tpl.yaml, templates/rhel6.tpl.yaml
Old guests like RHEL6 or CentOS6 require virtio-transitional
in newer libvirt/qemu versions, therefore a flag was added in the VM
template in order to signal the need for the virtio-transitional
configuration in the devices section.
Signed-off-by: Igor Bezukh <ibezukh@redhat.com>
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=1783192
```release-note
NONE
```
=> Adopt RHEL6 and Centos 6 templates to new libvirt/QEMU changes

templates/windows10.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml
When VMIO migrates a VM from RHV, it needs to be able to set the disk bus to "scsi".
This commit adds support for scsi in windows validation.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1912908
```release-note
add support for scsi disk bus in windows validation 
```
=> add support for scsi disk bus in windows validation 

builder/Dockerfile
sometimes tests fail due to dockerhub pull restrictions. This PR updates base image to newest fedora 33 and changes location from dockerhub to quay.
/cc @omeryahud 
```NONE
```
=> update base image for openshiftci

builder/Dockerfile
Signed-off-by: Kevin Wiesmueller <kwiesmul@redhat.com>
Prerequisite for https://github.com/kubevirt/common-templates/pull/298.
Adds the openshift python3 module to the CI builder.
```release-note
NONE
```
/assign @ksimon1
=> add python3-openshift to builder

automation/test-linux.sh, generate-templates.yaml, templates/fedora.tpl.yaml, templates/rhel7.tpl.yaml, templates/rhel8.tpl.yaml
This PR incorporates the emulator thread (isolation) feature into the templates.
This PR builds on top of:
- https://github.com/kubevirt/common-templates/pull/296
- https://github.com/kubevirt/common-templates/pull/297
- https://github.com/openshift/release/pull/14771
- https://github.com/openshift/release/pull/14788
- https://github.com/kubevirt/common-templates/pull/309
Also, this PR **requires** https://github.com/openshift/release/pull/14964 (in progress at the moment), which sets the appropriate compute (worker) node profile to be used in the tests with high performance settings, as discussed in prior PRs.
```release-note
NONE
```
=> Add emulator thread

templates/fedora.tpl.yaml
fix hard coded fedora name in annotations
**Which issue(s) this PR fixes** :
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1917210
``` 
fixed hard coded fedora name in annotations
```
=> fix hard coded fedora name in annotations

automation/unit-tests.sh, automation/validate-pvc-name-stability.py
Adds a test to ensure `SRC_PVC_NAME` and `SRC_PVC_NAMESPACE` do not change across upgrades.
Right now the test relies on the template names not changing across versions. If a template gets renamed the test won't fail as it's technically not the same template anymore.
```release-note
NONE
```
=> validate pvc name and namespace stability across upgrades

automation/test-linux.sh, templates/centos6.tpl.yaml, templates/rhel6.tpl.yaml
Old guests can now use virtio bus for disks and network interfaces
therefore configure the template to use that bus type as a default bus for them.
Signed-off-by: Igor Bezukh <ibezukh@redhat.com>
```release-note
Centos 6 and RHEL 6 based images to consume virtio bus for disks and network devices
```
=> Centos 6 and RHEL 6 to use virtio bus for network and storage by default

templates/fedora.tpl.yaml, templates/rhel7.tpl.yaml, templates/rhel8.tpl.yaml
**What this PR does / why we need it**: 
This PR expands I/O threads support for high performance templates. Specifically, these changes enforce the use of dedicated CPU placement (pinning) when I/O threads are enabled. Also, it dedicates an I/O thread for the root (main) disk.
```release-note
NONE
```
=> Expand I/O threads support for high performance templates

automation/test.sh
roll back to previous version version of CDI
newest version contain bug, which prevent VM to run
```
NONE
```
=> roll back to previous version version of CDI

README.md, generate-templates.yaml, templates/LABELS.md
Signed-off-by: cwilkers <cwilkers@redhat.com>
Updates Ansible playbook to create Ubuntu templates of latest LTS, 20.04 Focal Fossa
Depends on PR 318 in order to properly render Ubuntu templates
```release-note
Updates Ubuntu templates to 20.04 (Focal Fossa)
```
=> Bumped version of Ubuntu LTS from 18.04 to 20.04

automation/test-linux.sh, automation/test-windows.sh, automation/test.sh
tests don't have to fail during VM creation
If vm is not created due to some cluster issue, test doesn't have to fail,
beacuse the retry feature can create vm again.
Command which allows cpumanager on the nodes moved to test.sh script,
because it doesn't have to run everytime vm is created.
//cc @omeryahud 
```
NONE
```
=> Improve tests stability

generate-templates.yaml, templates/windows10.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml
This PR add support for multiqueue networking for Windows VMs. This requires two modifications:
- set `vmi.spec.domain.devices.networkInterfaceMultiqueue` appropriately; and
- set `vmi.spec.domain.devices.interfaces.model` to `virtio`.
The current proposal adds a template flag, `multiqueue` which is set to true for high performance Windows templates.
This flag is then processed in each template file to set the correct value for `devices.networkInterfaceMultiqueue` and `devices.interfaces.model`.
```release-note
NONE
```
=> Add support for multiqueue networking for high performance Windows templates

.github/workflows/release.yaml
The location of common-templates `Version` constant in the SSP operator has changed. This patch updates the release script to use the new location.
Do not merge until https://github.com/kubevirt/ssp-operator/pull/124 is merged.
```release-note
None
```
=> Update release script with new location of Version constant in SSP operator

automation/unit-tests.sh
Printing templates to stdout during testing so reviewers don't have to pull the patch and generate the templates themselves
```release-note
None
```
=> Print templates to stdout in CI

.github/workflows/release.yaml
Explicitly set the bundle version when generating it so it is correctly specified in the `template.kubevirt.io/version` label.
**Which issue(s) this PR fixes**
An issue where templates do not have the correct version in their version label
*Release note**:
```release-note
None
```
=> Explicitly set the version of the bundle when generating it for a release

version.sh
For reasons I do not know or remember the `v` from template versions is dropped when generating manifests.
I have checked with previous releases, and noticed it exists there, so I am not sure why it is dropped from this file.
I am changing this file to align with the requirement to have a full semver in our templates' version.
```release-note
None
```
=> Include full semver in release manifests

templates/fedora.tpl.yaml
fix hardcoded fedora name in annotations
```
NONE
```
=> [backport] fix hardcoded fedora name in annotations

automation/test.sh
Revert back to labeling only the worker nodes for high performace VM  tests
Fixes #
```release-note
```
=> Revert back to labeling only the worker nodes for high performace VM tests

dvtemplates/fedora_new_image.sh
Removes any spaces when collecting the Fedora version from the Fedora repository
```release-note
None
```
=> Remove any spaces when collecting the Fedora version from the Fedora repository

templates/VALIDATION.md, templates/centos6.tpl.yaml, templates/centos7.tpl.yaml, templates/centos8.tpl.yaml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/rhel6.tpl.yaml, templates/rhel7.tpl.yaml, templates/rhel8.tpl.yaml, templates/ubuntu.tpl.yaml, templates/windows10.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml
Update VMs in templates to API `v1`.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1936932
```release-note
Update VM API version to v1
```
=> Update VM API version from v1alpha3 to v1

automation/test-linux.sh, automation/test-windows.sh
Disable testing of high performance templates.
Due to missing cpu manager on testing nodes, we have to disable testing
of HP templates
```
NONE
```
=> Disable testing of high performance templates.

templates/centos6.tpl.yaml, templates/centos7.tpl.yaml, templates/centos8.tpl.yaml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/rhel6.tpl.yaml, templates/rhel7.tpl.yaml, templates/rhel8.tpl.yaml, templates/ubuntu.tpl.yaml, templates/windows10.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml
Signed-off-by: Shirly Radco <sradco@redhat.com>
Moved vm.kubevirt.io/os, vm.kubevirt.io/workload,
vm.kubevirt.io/flavor annotations under
spec.template.metadata so that they will be copied
to the VMI object.
They are used as labels for the kubevirt_vmi_phase_count metric.
Annotations from the new location are copied to the VMI.
Fixes #
```release-note
None
```
=> Fix os/flavor/workload annotations location

automation/test-linux.sh, automation/test-windows.sh, automation/test.sh
allow testing of HP templates
Enable CPU manager on ci nodes
The cpu manager is allowed only for templates, which have high performance variant. Other templates don't need it, because they don't have HP variant. I did it this way, because it takes about 10 minutes to enable cpu manager on nodes.
```
NONE
```
=> allow testing of HP templates

.github/workflows/validate-no-offensive-lang.yml, automation/validate-no-offensive-lang.sh, makefile
Add a check to the sannity test that fails if there is a usage
of offensive language in one of the files.
The script forbid the use of the words `master`, `slave`,
`blacklist` and `whitelist`
Sinse `master` is very common word as a name of default
branches or as a node name in clusters, the script allows
the usage of it if this word is part of a URL or a path.
The script does not check the file
.github/workflows/release.yaml
that may contains a lot if usage of the word `master`, which
referes to the master branch.
@ksimon1 Can you help me to trigger this check on every PR?
```
NONE
```
=> Validate that this repository does not contain offensive language

templates/rhel9.tpl.yaml
fix wrong api version in rhel 9 template
```
NONE
```
=> fix wrong api version in rhel 9 template

templates/centos6.tpl.yaml, templates/centos7.tpl.yaml, templates/centos8.tpl.yaml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/rhel6.tpl.yaml, templates/rhel7.tpl.yaml, templates/rhel8.tpl.yaml, templates/rhel9.tpl.yaml, templates/ubuntu.tpl.yaml, templates/windows10.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml
Revert "change datavolume api version to v1" 
According to storage team the v1 is not yet out
**Which issue(s) this PR fixes** :
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1997014
```
Revert "change datavolume api version to v1" 
```
=> Revert "change datavolume api version to v1" 

templates/centos6.tpl.yaml, templates/centos7.tpl.yaml, templates/centos8.tpl.yaml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/rhel6.tpl.yaml, templates/rhel7.tpl.yaml, templates/rhel8.tpl.yaml, templates/rhel9.tpl.yaml, templates/ubuntu.tpl.yaml, templates/windows10.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml
Revert "change datavolume api version to v1"
According to storage team the v1 is not yet out
**Which issue(s) this PR fixes** :
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1997014
```
Revert "change datavolume api version to v1" 
```
=> [release-v0.16] Reverts #370

automation/test-linux.sh, automation/test-windows.sh, automation/test.sh, templates/centos6.tpl.yaml, templates/centos7.tpl.yaml, templates/centos8.tpl.yaml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/rhel6.tpl.yaml, templates/rhel7.tpl.yaml, templates/rhel8.tpl.yaml, templates/rhel9.tpl.yaml, templates/ubuntu.tpl.yaml, templates/windows10.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml
Switch pvc to storage in datavolume spec
The storage type is similar to pvc but allows for some additional logic to be applied. It was introduced in order to implement detection and automation of storage parameters.
```
Switch pvc to storage in datavolume spec
```
=> switch pvc to storage in datavolume spec

templates/rhel9.tpl.yaml
change RHEL9 Alpha to Beta
updated osinfo-db
```
Change RHEL 9 Alpha to RHEL 9 Beta
```
=> change RHEL9 Alpha to Beta

automation/test-linux.sh, dvtemplates/build_k8s_cluster.sh
add patch which sets default accessMode and volumeMode
bump kubernetes version
This PR updates refreshes container image automation. Previously
automation failed, due to missing informations about acessMode and
volumeMode. With this change script always sets acessMode and volumeMode
to local storageProfile.
/cc @akrejcir 
```
NONE
```
=> add patch which sets default accessMode and volumeMode

.github/workflows/release.yaml
fix github actions release script
common-templates file were moved in ssp operator
to different folder (https://github.com/kubevirt/ssp-operator/pull/238). They no longer exists in
internal/operands/common-templates/data/common-templates-bundle/
```
NONE
```
=> fix github actions release script

README.md, automation/test-linux.sh, automation/test-windows.sh, automation/unit-tests.sh, automation/validate-pvc-name-stability.py, templates/README.md, templates/centos6.tpl.yaml, templates/centos7.tpl.yaml, templates/centos8.tpl.yaml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/rhel6.tpl.yaml, templates/rhel7.tpl.yaml, templates/rhel8.tpl.yaml, templates/rhel9.tpl.yaml, templates/ubuntu.tpl.yaml, templates/windows10.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml
This indirection allows easier update of PVCs, because the DataSource can be updated when a new PVC is imported.
```release-note
Changed DataVolume source from PVC to DataSource.
```
=> Change DataVolume source from PVC to DataSource

README.md, automation/test-linux.sh, automation/test-windows.sh, automation/unit-tests.sh, automation/validate-pvc-name-stability.py, templates/README.md, templates/centos6.tpl.yaml, templates/centos7.tpl.yaml, templates/centos8.tpl.yaml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/rhel6.tpl.yaml, templates/rhel7.tpl.yaml, templates/rhel8.tpl.yaml, templates/rhel9.tpl.yaml, templates/ubuntu.tpl.yaml, templates/windows10.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml
These names are used by the UI, the new names would break it.
```release-note
None
```
=> Revert parameter names back to SRC_PVC_NAME and SRC_PVC_NAMESPACE

builder/Dockerfile, dvtemplates/new_cdi_image.sh
mirror.openshift.com is retired, let's avoid referencing it.
```release-note
NONE
```
=> Update openshift mirror URL to working one

templates/fedora.tpl.yaml
Change the image download URL recommended on fedora templates from 32 -> 34 since the templates are created with Fedora 34+
```
NONE
```
=> Change recommended disk image url 32 -> 34

templates/windows10.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml
highperformance windows templates now uses virtio for storage
**Which issue(s) this PR fixes** :
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2018457
```release-note
highperformance windows templates now uses virtio for storage
```
=> highperformance windows templates now uses virtio for storage

automation/unit-tests.sh, templates/rhel8.saphana.tpl.yaml
This PR improves the following aspects of the hana template:
* Use the `registry.redhat.io` registry instead of `registry.access.redhat.com`
* Make SRIOV parameters required, since they always have to be adjusted to the environment
* Give users the freedom to set the node selectors freely
* Add a blanko toleration which helps scheduling the VM to exclusively dedicated nodes
Fixes #
```release-note
Use the correct RHEL containerdisk URL, make SRIOV resource names required and make node selection more flexible
```
=> Adjust hana template parameter details

templates/rhel8.saphana.tpl.yaml
The kubevirt validation allows passing through models on sriov devices
which it should not, and they have no effect. Removing them.
Fixes #
```release-note
NONE
```
=> Remove virtio model reference on sriov

README.md, automation/test-linux.sh, automation/test-windows.sh, automation/unit-tests.sh, automation/validate-pvc-name-stability.py, templates/README.md, templates/centos-stream8.tpl.yaml, templates/centos-stream9.tpl.yaml, templates/centos6.tpl.yaml, templates/centos7.tpl.yaml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/rhel6.tpl.yaml, templates/rhel7.tpl.yaml, templates/rhel8.tpl.yaml, templates/rhel9.tpl.yaml, templates/ubuntu.tpl.yaml, templates/windows10.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml
Rename from SRC_PVC_NAME to DATA_SOURCE_NAME,
and from SRC_PVC_NAMESPACE to DATA_SOURCE_NAMESPACE.
```release-note
Renamed parameters in templates.
```
=> Rename parameters to DATA_SOURCE_NAME and DATA_SOURCE_NAMESPACE

osinfo-db-override/os/centos.org/centos-stream-8.xml, osinfo-db-override/os/centos.org/centos-stream-9.xml, osinfo-db-override/os/opensuse.org/opensuse-15.2.xml, osinfo-db-override/os/opensuse.org/opensuse-15.3.xml
Add osinfo-db overrides for distributions without cloud images, so
templates with image urls can be generated. 
Remove these overrides when cloud images are added to the distributions
in upstream osinfo-db.
```release-note
None
```
=> Add osinfo-db overrides for distributions without cloud images

templates/centos-stream8.tpl.yaml, templates/centos-stream9.tpl.yaml, templates/centos6.tpl.yaml, templates/centos7.tpl.yaml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/rhel6.tpl.yaml, templates/rhel7.tpl.yaml, templates/rhel8.tpl.yaml, templates/rhel9.tpl.yaml, templates/ubuntu.tpl.yaml, templates/windows10.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml
The first hard disk is called by the name of the machine instead of by it's actual purpose
This creates an anomaly when printing out the names of  disk
``` bash
oc get template rhel6-server-large -n default -o json | \
jq '.objects[0].spec.template.spec.domain.devices.disks[] | "\(.name)"'
"${NAME}"
"cloudinitdisk"
```
Expected results should be:
``` bash
oc get template rhel6-server-large -n default -o json | \
jq '.objects[0].spec.template.spec.domain.devices.disks[] | "\(.name)"'
"rootdisk"
"cloudinitdisk"
```
```release-note
NONE
```
=> Rename the first HD rootdisk

generate-templates.yaml, templates/centos-stream8.tpl.yaml, templates/centos-stream9.tpl.yaml, templates/centos7.tpl.yaml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/rhel8.tpl.yaml, templates/rhel9.tpl.yaml, templates/ubuntu.tpl.yaml
This adds the annotations `template.kubevirt.io/containerdisks` and
`template.kubevirt.io/images` to the common templates where appropriate.
The annotations can be used to automatically download guest images or to
display instructions for the user.
Both annotations contain lists where each element is separated by a new
line.
Image URLs are automatically obtained from the osinfo-db. Containerdisks are
static for now. (until containerdisks are added to libosinfo)
**Which issue(s) this PR fixes**
https://bugzilla.redhat.com/show_bug.cgi?id=2031155
https://bugzilla.redhat.com/show_bug.cgi?id=2038832
https://bugzilla.redhat.com/show_bug.cgi?id=2031857
Merge after #412 and #413, rebase first …
=> Add annotations for containerdisks and import URLs

builder/Dockerfile
Download the latest stable oc binary in `builder/Dockerfile` from the new
location on the mirror.
intltool was removed by accident from the dependencies. Readd it.
```release-note
None
```
=> Download oc binary from new location and readd intltool

builder/Dockerfile
Follow redirects (if there are any) when downloading oc and yq binaries
in `builder/Dockerfile`, so instead of a redirection page the actual
binaries are received.
```release-note
None
```
=> Follow redirects when downloading oc and yq

.github/workflows/update-osinfo-db.yaml, makefile
Add a GitHub action to periodically update the `osinfo-db` submodule to
the latest libosinfo/osinfo-db master.
```release-note
None
```
=> Update osinfo-db on schedule

generate-templates.yaml, templates/fedora.tpl.yaml
modify fedora template that support UEFI BIOS with secure boot by default.
Fixes #
- UEFI BIOS is work with fedora35+
```release-note
modify fedora template to have secure boot support
```
=> modify fedora template to start with secure boot support

osinfo-db-override/os/opensuse.org/opensuse-15.2.xml, osinfo-db-override/os/opensuse.org/opensuse-15.3.xml
The links added by the overrides are now included in upstream osinfo-db.
```release-note
None
```
=> Remove openSUSE osinfo-db overrides

templates/rhel9.tpl.yaml
SecureBoot will be enabled to follow KubeVirt's
default setting.
Signed-off-by: Antonio Cardace <acardace@redhat.com>
Fixes #
```release-note
Enable UEFI by default for the RHEL 9 template
```
=> Have RHEL 9 template use UEFI by default

.github/workflows/release.yaml, dvtemplates/build_k8s_cluster.sh, dvtemplates/new_cdi_image.sh
Change docker commands into podman
```
Removes all docker references and replaces them with podman.
```
Signed-off-by: Ondrej Pokorny <opokorny@redhat.com>
=> Change docker commands into podman

templates/ubuntu.tpl.yaml
This adds the containerdisks annotation to the Ubuntu template.
```release-note
Add containerdisks annotation to Ubuntu template
```
=> Add containerdisks annotation to Ubuntu template

README.md, automation/test-windows.sh, generate-templates.yaml, osinfo-db-override/os/microsoft.com/win-11.xml, templates/windows10.tpl.yaml, templates/windows11.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml
Signed-off-by: fossedihelm <ffossemo@redhat.com>
Add windows 11 template. Windows 11 information currently is not present in osinfo-db (there is an open PR [https://gitlab.com/libosinfo/osinfo-db/-/merge_requests/362](https://gitlab.com/libosinfo/osinfo-db/-/merge_requests/362)); fot this reason has been added an entry fot it in [https://github.com/kubevirt/common-templates/tree/master/osinfo-db-override/os](https://github.com/kubevirt/common-templates/tree/master/osinfo-db-override/os)
This PR requires [https://github.com/kubevirt/kubevirt/pull/7103](https://github.com/kubevirt/kubevirt/pull/7103) since the latter introduce the TPM 2.0 support, required by Windows 11
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes …
=> Add windows 11 template

templates/fedora.tpl.yaml
Because Fedora increases it's major version quickly, an old
version in the display name might confuse the user.
The minimal required Fedora version is still mentioned in the
description.
Signed-off-by: Dominik Holler <dholler@redhat.com>
Fixes #
```release-note
Remove version information from fedora display name
```
=> Remove version information from fedora display name

templates/fedora.tpl.yaml
bump fedora containerdisk to 36
```
bump fedora containerdisk to 36
```
=> bump fedora containerdisk to 36

templates/rhel9.tpl.yaml
backport of https://github.com/kubevirt/common-templates/pull/449
```
Update RHEL 9 template
```
=> [release-v0.19] Updating RHEL 9 Template name and description

templates/rhel9.tpl.yaml
backport of https://github.com/kubevirt/common-templates/pull/449
```
Update RHEL 9 template
```
=> [release-v0.16] Updating RHEL 9 Template name and description

templates/fedora.tpl.yaml
This ensures that the latest available Fedora version is always used.
```release-note
Use latest fedora containerdisk
```
=> Use latest fedora containerdisk

generate-templates.yaml, osinfo-db-override/os/redhat.com/rhel-6.10.xml, osinfo-db-override/os/redhat.com/rhel-7.9.xml, osinfo-db-override/os/redhat.com/rhel-8.6.xml, osinfo-db-override/os/redhat.com/rhel-9.0.xml, templates/rhel6.tpl.yaml, templates/rhel7.tpl.yaml, templates/rhel8.tpl.yaml, templates/rhel9.tpl.yaml
This adds osinfo-db overrides to provide links to the RHEL download
pages where KVM Guest Image links can be acquired.
See here for example:
```release-note
Add image URLs to RHEL templates
```
=> Add image URLs to RHEL templates

automation/test-windows.sh, automation/test.sh
disable cdi garbage collector in e2e tests
this prevent deletion of imported datavolumes with operating systems 
Update script which retrieves kubevirt and cdi versions (previous solution is not working anymore)
```
NONE
```
=> disable cdi garbage collector in e2e tests

generate-templates.yaml, osinfo-db-override/os/centos.org/centos-stream-8.xml, osinfo-db-override/os/centos.org/centos-stream-9.xml, templates/centos-stream8.tpl.yaml, templates/centos-stream9.tpl.yaml, templates/centos7.tpl.yaml, templates/fedora.tpl.yaml, templates/ubuntu.tpl.yaml
With this change containerdisk urls for the templates are loaded from osinfo-db instead of specifying them manually (where applicable).
Overrides for centos-stream[8|9] are still needed because of CentOS still having no stable image urls. Containerdisks are added there for now too. The image urls are updated to the latest version.
Fixes #
```release-note
None
```
=> Use containerdisk urls provided by osinfo-db

templates/windows2k22.tpl.yaml
Signed-off-by: bmordeha <bmodeha@redhat.com>
Windows 2022 template is missing vTPM and UEFI
Fixes #
```release-note
add vTPM and UEFI to Windows 2022 template
```
=> Windows 2022 template is missing vTPM and UEFI

templates/centos6.tpl.yaml, templates/centos7.tpl.yaml, templates/rhel7.tpl.yaml, templates/rhel8.tpl.yaml, templates/rhel9.tpl.yaml
"Red Hat Enterprise Linux 9 VM" is visually cleaner and more precise display name now that RHEL 9.1 is available as is the default.
```release-note
NONE
```
=> improve RHEL9 display name

automation/test-windows.sh
increase timeout for windows vms in tests
Increase timeout for waiting for VM to be up.
This should fix failing tests in https://github.com/openshift/release/pull/34167
```
NONE
```
=> increase timeout for windows vms in tests

automation/test-windows.sh
increase timeout for windows vms and datavolume in tests
Increase timeout for waiting for VM and datavolume to 1 hour to be up.
```
NONE
```
=> increase timeout for windows vms and datavolume in tests

automation/test.sh
switch to ssd storageClass in windows tests
the non ssd storageclass is causing timeout on GCP OCP 4.12 windows tests. This commit changes the default storageClass to ssd.
```
NONE
```
=> switch to ssd storageClass in windows tests

automation/test.sh
fix: improve the condition for switching storageclass in e2e test
fix: changed order of applied annotations for storageclass in e2e test
```
NONE
```
=> fix: improve the condition for switching storageclass in e2e test

README.md
RHEL 9 is no longer Beta and it is already GA.
Signed-off-by: Ben Oukhanov <boukhanov@redhat.com>
Remove "Beta" from RHEL 9 Guest OS name in README.md.
N/A
N/A
```release-note
N/A
```
=> docs: remove beta from rhel 9 guest os

automation/test.sh
fix: remove TSC labels from worker nodes in e2e tests
Latest kubevirt version introduced tsc node selectors for windows vms. This is causing problems during scheduling of windows VM, which are in pending state, due to different tsc labels on nodes. Currently there is no easy fix in kubevirt, because it would break migration flow. Due to that, we have to disable node-labeller and remove the tsc labels from nodes, so virt-controller can schedule the VMs on more nodes. This approach will break migration flow, but in our tests we do not test it.
```
NONE
```
=> fix: remove TSC labels from worker nodes in e2e tests

automation/test-linux.sh, automation/test-windows.sh
fix: add bind immediate annotation to test datavolume
the default storageClass in e2e tests requests WFFC mode. Currently when original datavolume is created in e2e tests, it is in pending state, because there is no object which will consume it. This commit adds special annotation
cdi.kubevirt.io/storage.bind.immediate.requested
to windows and linux original datavolume,
which allows to import datavolume without consumer.
```
NONE
```
=> fix: add bind immediate annotation to test datavolume

generate-templates.yaml
fix: increase required memory for ubuntu small template
feat: update osinfo db to latest
Newest ubuntu 23.4 requires at least 3GB memory. This commit updates small ubuntu template. It increases memory request to 3GB.
```
Increase memory request in ubuntu small template to 3GB
update osinfo-db to latest
```
=> fix: increase required memory for ubuntu small template

automation/test-windows.sh, templates/windows2k12.tpl.yaml
This PR adds an annotation to the Windows Server 2012 R2 template to tag it as deprecated.
Fixes #
```release-note
Windows Server 2012 R2 is now deprecated
```
=> Annotate Windows Server 2012 as deprecated

builder/Dockerfile
feat: add podman to builder image
To make ci work again, we will need to have podman in test env. Podman will help to download VM image and push it to internal ocp registry
```
NONE
```
=> feat: add podman to builder image

templates/windows10.tpl.yaml, templates/windows11.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml, templates/windows2k22.tpl.yaml
Added the version of Windows to the names of virtual machines.
https://bugzilla.redhat.com/show_bug.cgi?id=2151413
```release-note
Windows VM names include versions.
```
=> Add windows version to VM name

OWNERS
Remove 'codingben' from the OWNRES
```release-note
None
```
=> Remove 'codingben' from the OWNRES

templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml
Adopt UEFI in Windows 2k12, 2k16 and 2k19 by enabling EFI and Secureboot in the respective templates.
Adopt UEFI in Windows 2k12, 2k16 and 2k19 by enabling EFI and Secureboot in the respective templates.
Fixes #
```release-note
Adopted UEFI in Windows 2k12, 2k16 and 2k19 by enabling EFI and Secureboot in the respective templates.
```
=> Adopt UEFI in Windows 2k12, 2k16 and 2k19

templates/centos-stream8.tpl.yaml, templates/centos-stream9.tpl.yaml, templates/centos6.tpl.yaml, templates/centos7.tpl.yaml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/rhel7.tpl.yaml, templates/rhel8.tpl.yaml, templates/rhel9.tpl.yaml, templates/ubuntu.tpl.yaml, templates/windows10.tpl.yaml, templates/windows11.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml, templates/windows2k22.tpl.yaml
/cc @0xFelix 
/cc @ksimon1 
The current set of templates are only verified on amd64 so to avoid users attempting to run them on aarch64 etc set the architecture within the VirtualMachineInstanceSpec.
Fixes #
```release-note
The architecture of each `VirtualMachine` is now  set to `amd64` within the `VirtualMachineInstanceSpec`.
```
=> Set architecture to amd64 across all templates

generate-templates.yaml
chore: drop fedora tiny templates
newest fedora 40 has 2Gi required memory. This means, tiny template
does not have accomplished with minimal requirements and will be
dropped.
```
Drop Fedora tiny templates
```
/cc @0xFelix, @lyarwood, @dominikholler, @geetikakay
=> chore: drop fedora tiny templates

templates/centos-stream8.tpl.yaml, templates/centos-stream9.tpl.yaml, templates/centos6.tpl.yaml, templates/centos7.tpl.yaml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/rhel7.tpl.yaml, templates/rhel8.tpl.yaml, templates/rhel9.tpl.yaml, templates/ubuntu.tpl.yaml, templates/windows10.tpl.yaml, templates/windows11.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml, templates/windows2k22.tpl.yaml
VM templates are using spec.running and should use spec.runStrategy instead because spec.running is
planned to be deprecated soon.
Fixes #581
```release-note
Use spec.runStrategy instead of spec.running
```
=> feat: use spec.runStrategy instead of spec.running

templates/centos-stream8.tpl.yaml, templates/centos-stream9.tpl.yaml, templates/centos6.tpl.yaml, templates/centos7.tpl.yaml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/rhel7.tpl.yaml, templates/rhel8.tpl.yaml, templates/rhel9.tpl.yaml, templates/ubuntu.tpl.yaml, templates/windows10.tpl.yaml, templates/windows11.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml, templates/windows2k22.tpl.yaml
Enable networkInterfaceMultiqueue only if the amount of sockets is greater than one, since networkInterfaceMultiqueue requires at least two sockets.
Fixes #
```release-note
networkInterfaceMultiqueue is only enabled if the template has more than one socket
```
=> fix: Enable networkInterfaceMultiqueue only if sockets > 1

automation/unit-tests.sh, makefile
The 'make generate' command is currently being called within the unit-test script instead of being added as a dependency in the makefile.
The 'make generate' command is currently being called within the unit-test script instead of being added as a dependency in the makefile.
Fixes #
```release-note NONE
```
=> fix: make generate called inside unit-test.sh

automation/unit-tests.sh
To enable running the unit tests multiple times, the existing templates are deleted before creating new ones. This approach allows for the successful execution of unit tests even if the templates already exist in the cluster.
If the templates do not exist, the 'oc delete' command would fail, which is why '|| true' is used.
**What this PR does / why we need it**: ability to run unit tests consecutively
Fixes #
```release-note NONE
```
=> fix: make unit-tests can be called more than once

builder/Dockerfile
To ensure early failure in the unit tests, it is necessary to verify the installation of the Python OpenShift package. One effective way to accomplish this is by using the pip show command. Therefore, we need to enhance the Dockerfile to include pip.
**What this PR does / why we need it**: Fail early
Fixes #
```release-note NONE
```
=> fix: add pip to builder/Dockerfile

templates/centos-stream8.tpl.yaml, templates/centos7.tpl.yaml
Mark CentOS 7 and Stream 8 as deprecated with recent EOLs
Fixes #
```release-note
CentOS 7 and Stream 8 templates are now deprecated
```
=> centos-7,centos-stream8: Mark as deprecated with recent EOLs

automation/unit-tests.sh
The unit-tests.sh script may fail at an advanced stage if the python openShift module is not installed. Failing at the initial step alerts the user to this requirement.
**What this PR does / why we need it**: Fail early
Fixes #
```release-note NONE
```
=> fix: verification of the python openshift requirement

makefile
This change enables the use of 'make update-osinfo-db' without the need for any additional steps.
**What this PR does / why we need it**: User friendly
Fixes #
```release-note NONE
```
=> fix: add submodule initialization in update-osinfo-db

automation/test.sh
This error was identified while using CodeReady Workspaces with limited resources. The DataVolume specified in the test-linux.sh file did not fully deploy, resulting in failed end-to-end tests.
**What this PR does / why we need it**: fixes error
Fixes #
```release-note NONE
```
=> fix: patching cdi after availability

automation/test-linux.sh
fix: remove tiny size from e2e test for fedora
the fedora tiny size was removed and e2e test is failing because it is trying to create vm with it.
```
NONE
```
=> fix: remove tiny size from e2e test for fedora

automation/test.sh
Fixes #
```release-note NONE
```
=> feat: enable virtctl download based on host architecture

automation/test-linux.sh, automation/test-windows.sh
fix: use spec.storage in DV in e2e tests
Switch to spec.storage in e2e tests DVs.
This should fix the 500 error we are experiencing during the
clone of the VM disk.
```
NONE
```
=> fix: use spec.storage in DV in e2e tests

.gitignore, automation/test.sh
The template validator code is now located in the ssp-operator repository. To deploy the validator exclusively, additional changes are required in the ssp. However, experimentation indicates that these changes are not necessary for the end-to-end tests to function properly.
Fixes #
```release-note NONE
```
=> fix: remove call to legacy template validator

automation/test.sh, templates/windows11.tpl.yaml, templates/windows2k22.tpl.yaml
The Windows 11 template enables TPM and EFI, since both a required. However, they were both non-persistent by default, which means bitlocker won't work. Also, in recent versions of Windows 11, bitlocker requires both TPM and EFI to be persistent. This enables persistent EFI and TPM, which requires a RWO FS storage class to be present.
Fixes #
```release-note
Windows 11 now defaults to persistent TPM and EFI. This requires a storage class capable of ReadWriteMany Filesystem
```
=> Windows 11: enable TPM and EFI persistence

makefile
The primary purpose of this addition is to clean up the dist/templates folder. This cleanup process aids in debugging the ansible scripts.
Fixes #
```release-note NONE
```
=> fix: add make clean

automation/test-linux.sh, generate-templates.yaml
This commit disables the generation of templates for the s390x architecture, as there are no references to CentOS 6 in the osinfo-db for this architecture.
Fixes #
```release-note NONE
```
=> feat: disable Centos 6 on s390x architecture

generate-templates.yaml, osinfo-db-override/os/microsoft.com/win-2k25.xml, templates/windows2k25.tpl.yaml
chore: add Windows Server 2k25 template
The OS has medium and large flavor, server and highperformance workload.
```
chore: add Windows Server 2k25 template
```
=> chore: add Windows Server 2k25 template

osinfo-db-override/os/microsoft.com/win-2k25.xml, templates/windows2k25.tpl.yaml
fix: fix minimum requirements in win2k25 template
The win2k25 requirements https://learn.microsoft.com/en-us/windows-server/get-started/hardware-requirements?tabs=cpu#components
```
NONE
```
=> fix: fix minimum requirements in win2k25 template

automation/test-linux.sh
This change resolves an issue where manually starting the Fedora end-to-end tests was not possible due to invalid workload values. It is important to note that the Fedora templates have changed the sizes, while the workloads remain the same, only including small, medium, and large.
Fixes #
```release-note
NONE
```
=> fix: fedora workloads definition in function tests

builder/Dockerfile
feat: add ssh client to builder image
New Windows images in e2e tests will use ssh instead of winrm cli approach.
```
NONE
```
=> feat: add ssh client to builder image

templates/README.md
Just a small README update
```release-note
NONE
```
=> README: use spec.runStrategy instead of spec.running

generate-templates.yaml, templates/fedora.tpl.yaml
Fedora offers images for a variety of architectures, which can be included as a template parameter. Within the template, there is a specific parameter for defining the architecture.
For the sake of simplicity, I have currently set the host architecture.
Fixes #
```release-note
NONE
```
=> feat: multiarch fedora template.

templates/fedora.tpl.yaml
Attempting to run it on other architectures (e.g., s390x) makes the image unbootable.
Fixes #
```release-note
NONE
```
=> fix: disable efi bootloader in fedora for s390x

automation/test.sh
This optimization is particularly beneficial when running the test scripts a second time within the same cluster.
Fixes #
```release-note
NONE
```
=> perf: optimizes check for updated machineconfigpool

automation/test-linux.sh
The templates generated for Ubuntu are not of the tiny variant. The end-to-end tests attempted to run them but failed silently.
Fixes #
```release-note
NONE
```
=> fix: address failing tests on Ubuntu

automation/test-linux.sh
In some cases, the current timeout of 600 seconds is insufficient for starting a virtual machine (VM). To address this issue, we propose increasing the timeout to 900 seconds, which should provide adequate time for the VM to start successfully.
Fixes #
```release-note
NONE
```
=> fix: increase timeout for end-to-end tests

automation/connect_to_rhel_console.exp, automation/test-linux.sh
The issue identified was that the string "1" is recognized as a pattern. The latest version of CentOS Stream 9 includes this "pattern" in its boot sequence.
Fixes #
```release-note
NONE
```
=> fix: patterns in expect script and adjust timeout/exit conditions

automation/test-linux.sh
The only image that remains in legacy status is CentOS 6. The link https://quay.io/repository/containerdisks/centos?tab=tags currently contains only CentOS 7 and CentOS 8 images.
Fixes #
```release-note
NONE
```
=> fix: update legacy containerdisks url

automation/test-linux.sh, generate-templates.yaml, makefile, templates/fedora.tpl.yaml
The default value is x86_64, but it can be overridden. This change ensures compatibility with older versions.
Fixes #
```release-note
NONE
```
=> feat: target archictecture as a parameter

generate-templates.yaml
Fixes #
```release-note
NONE
```
=> feat: disable distributions incompatible with s390x architecture

builder/Dockerfile
fix: creation of /.ansible folder in builder dockerfile
the automation for releases stopped working because of error with folder permission (https://github.com/kubevirt/common-templates/actions/runs/12034572916).
By changing the command to RUN mkdir -m 777 -p /.ansible/tmp the release automation started working (https://github.com/ksimon1/common-templates/actions/runs/12037461414/job/33560963925#step:4:1092).
```
NONE
```
=> fix: creation of /.ansible folder in builder dockerfile

.github/workflows/release.yaml, makefile
Create separate bundle files and upload them.
Also, release action will push both bundles to
ssp-operator
Fixes #
```release-note
Create separate bundles for specific architectures
```
=> release: split bundle files for different arches

automation/test-windows.sh
fix: Windows e2e tests
Windows images now uses only 4.99 tag
fix: use AgentConnected status condition to recognize if Windows VM is up
removed retry of mechanism of starting the VM, since it is not require
any more.
Changed the way how to recognize if Windows vms are up are ready. Tests
now uses AgentConnected status condition which is set, when vm is up.
```release-note
NONE
```
=> fix: Windows e2e tests
