kubevirt/common-templates

.travis.yml
=> Update to KubeVirt v0.8.0-alpha.0

.travis.yml
=> ci: Test with Kubernetes 1.11

.travis.yml, makefile
=> test: Also output console

.gitignore, .gitmodules, .travis.yml, makefile, test.sh
This allows us to leverage the existing infrastructure for running functional tests on travis
=> ci: Use traviskube

makefile
=> tests: Small refactor

README.md
=> README: Update travis build status

templates/fedora28.yaml, templates/opensuse15.yaml, templates/rhel75-hp.yaml, templates/rhel75.yaml, templates/ubuntu1804.yaml, templates/win2k12r2.yaml
=> correct urls in templates

.gitignore, .travis.yml, makefile
This makes it easier to package and ship the templates as every version has a distinct filename.
=> Version the released common-templates yaml file

README.md
Fix two commands in the user manual
=> fix user manual: git submodules

.gitmodules, automation/test.mounts, automation/test.packages, automation/test.sh, stdci.yaml
script which tests windows template in stdci.
=> add windows test

templates/_linux.yaml, templates/win2k12r2.tpl.yaml
This label allows us to use kubectl expose as described
here https://github.com/kubevirt/kubevirt/issues/1686
=> Add app: ${VM_NAME} label to every VM

automation/test.sh
This patch updates kubevirt version in windows test to 0.11 (because of KUBEVIRT_MEMORY_SIZE variable), updates windows image download function (now it should not timeout because of download lock), removes restriction for vm memory size (now we can set more memory for node)
=> Fix windows test

.travis.yml, automation/test.sh, generate-templates.yaml, makefile, templates/_linux.yaml, templates/win2k12r2.tpl.yaml
Add support for sockets and threads in templates
=> Add support for CPU sockets and threads

templates/README.md, templates/VALIDATION.md
Add documentation for the validation annotation, to be consumed by the UI tools.
=> Template validation docs

templates/centos6.tpl.yaml, templates/centos7.tpl.yaml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/rhel6.tpl.yaml, templates/rhel7.tpl.yaml, templates/ubuntu.tpl.yaml, templates/win2k12r2.tpl.yaml
Fixes https://github.com/kubevirt/common-templates/issues/60
=> Fix #60 - template api version

.travis.yml, README.md, automation/test.sh, generate-templates.yaml, makefile, templates/README.md
removed generic workload - replaced by desktop/server workloads
updated tests
@MarSik please review
=> removed generic workload

templates/_linux.yaml
- Add single default pod networking nic
- Add metadata for template so expose port in virtctl works
- Add cloudinit disk so cloud init works
=> Several additions to base Linux template

.travis.yml, automation/check-patch.rhel7.mounts, automation/check-patch.rhel7.packages, automation/check-patch.rhel7.sh, automation/test-rhel.sh, automation/test.sh, stdci.yaml
This PR adds stdci test for rhel 7.
=> add rhel 7 stdci test

automation/check-patch.rhel8.packages, automation/check-patch.windows10.mounts, automation/check-patch.windows10.packages, automation/check-patch.windows10.sh, automation/check-patch.windows2012.mounts, automation/check-patch.windows2012.packages, automation/check-patch.windows2012.sh, automation/check-patch.windows2016.packages, automation/test-windows.sh, automation/test.sh, stdci.yaml
This PR adds stdci tests for windows2012, win 10.
=> add windows2012, win 10 stdci tests

.travis.yml, automation/check-patch.rhel6.mounts, automation/check-patch.rhel6.packages, automation/check-patch.rhel6.sh, automation/test-rhel.sh, automation/test-windows.sh, automation/test.sh, stdci.yaml
=> RHEL6 stdci test

automation/check-patch.windows2019.mounts, automation/check-patch.windows2019.packages, automation/check-patch.windows2019.sh, automation/test-windows.sh, automation/test.sh, stdci.yaml
This PR adds windows 2019 stdci test
=> add windows 2019 stdci test

.travis.yml, makefile, revision.sh, templates/_linux.yaml, templates/centos6.tpl.yaml, templates/centos7.tpl.yaml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/rhel6.tpl.yaml, templates/rhel7.tpl.yaml, templates/ubuntu.tpl.yaml, templates/win2k12r2.tpl.yaml, version.sh
We need to know from which version of a template a VM was baked.
Signed-off-by: Francesco Romani <fromani@redhat.com>
=> templates: add versioning information

templates/VALIDATION.md
Related to: https://github.com/fromanirh/kubevirt-template-validator/pull/20
This pr added description of justWarning flag into validation documentation.
/cc @MarSik, @fromanirh
=> added description of justWarning flag into validation documentation

templates/win2k12r2.tpl.yaml
This PR adds warning validation to windows templates. It checks if vm has virtio disk bus.
/cc @MarSik, @fromanirh
=> win templates: add warning virtio bus validation

automation/test-rhel.sh, automation/test-windows.sh, automation/test.sh, stdci.yaml
this PR fixes check if win vms are up, adds retry logic, disables win2k19 test
=> templates: fix windows test

.gitignore, .gitmodules, .travis.yml, create-minikube-pvc.sh, makefile
ci submodule is automatically fetching latest kubevirt
=> updated ci submodule to latest version

.travis.yml, makefile, travis_ci/test.sh, travis_ci/test_syntax.sh
travis tests are now in separate bash files.
removed unnecessary commands in makefile
=> Refactoring of travis tests

.travis.yml, automation/check-patch.rhel8.packages, automation/check-patch.windows2016.packages, lookup_plugins/osinfo.py, templates/_linux.yaml, templates/win2k12r2.tpl.yaml
This PR fixes multiple different issues wrt osinfo data usage.
=> Fixes osinfo

generate-templates.yaml, osinfo-db-override/os/redhat.com/rhel-8.1.xml
=> add support for rhel8.1

README.md
Signed-off-by: Arik Hadas <ahadas@redhat.com>
=> Fix examples on the README page

.travis.yml, travis_ci/check-validations.py, travis_ci/test_syntax.sh
this validation checks if validation is in correct json format
Fixes https://github.com/kubevirt/common-templates/issues/115
/cc @petrkotas, @fromanirh 
=> add json validation for validation in common-templates

travis_ci/test.sh
=> changed download URL for centos8 image

automation/test-windows.sh, generate-templates.yaml, templates/windows10.tpl.yaml
add new windows 10 template.
This template is separate from other windows template, because
it has different requirements.
=> add new windows 10 template.

automation/test-rhel.sh, generate-templates.yaml
Template cannot be deleted, because of backward compatibility.
=> Revert #129

automation/test.sh
The image 'cockpit/kubernetes' is no longer in dockerhub,
which causes the pod 'registry-console' to fail to start.
With this patch, the pod is ignored when checking for readiness.
Signed-off-by: Andrej Krejcir <akrejcir@redhat.com>
=> Fix 'automation/test.sh' waiting for failed pod

generate-templates.yaml, templates/rhel8.tpl.yaml
rhel8 used rhel7 description. This PR adds rhel8 description
=> Fix rhel8 description

templates/centos6.tpl.yaml, templates/centos7.tpl.yaml, templates/centos8.tpl.yaml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/rhel6.tpl.yaml, templates/rhel7.tpl.yaml, templates/rhel8.tpl.yaml, templates/ubuntu.tpl.yaml, templates/win2k12r2-deprecated.tpl.yaml, templates/windows.tpl.yaml, templates/windows10.tpl.yaml
The original descriptions were unnecessarily long.
Signed-off-by: Andrej Krejcir <akrejcir@redhat.com>
=> Make template descriptions shorter

README.md
Added supported OSes, deprecated templates.
=> updated README.md file.

generate-templates.yaml
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1827705
=> enable tablet device for windows server editions

.travis.yml, automation/test-rhel.sh, automation/test-windows.sh, automation/test.sh, travis_ci/test.sh
This PR integrates template validator in common-templates test suite
=> Integrate template validator in test suite

.travis.yml
=> Changed the ssp-operator owner to the kubevirt org

automation/test-rhel.sh, automation/test-windows.sh, automation/test.sh, makefile
integrate common-template tests into openshift ci 
DO NOT MERGE
/hold
=> [WIP] integrate common-template tests into openshift ci

automation/test.sh, builder/Dockerfile, makefile
=> add builder image for openshift ci

automation/test.sh
=> add install commands

automation/test.sh
=> add debug commands

automation/test.sh, builder/Dockerfile
=> add docker handling commands

automation/test.sh
=> replaced docker command with oc solution

automation/test.sh
=> add namespace

automation/test.sh, builder/Dockerfile
=> remove oc command which deploys common-template builder

builder/Dockerfile
=> add findutils package

builder/Dockerfile
=> add user UID into dockerfile

builder/Dockerfile
=> remove user UID

builder/Dockerfile
=> Dockerfile: set permissions on /etc/passwd file

automation/test-rhel.sh, automation/test.sh
=> remove command to copy connect_to_rhel_console.exp script

automation/test.sh
=> replace apps/v1beta1 with apps/v1 for template validator

automation/test.sh
=> fix sed command

automation/test.sh
=> disable template validator

automation/test-rhel.sh, automation/test.sh, builder/Dockerfile
=> add qemu package to dockerfile

automation/test.sh
=> remove chown command

automation/test.sh, create-minikube-pvc.sh
=> added namespace in PV and PVC

templates/_linux.yaml, templates/windows.tpl.yaml, templates/windows10.tpl.yaml
change default PVC namespace
```
NONE
```
=> change default PVC namespace

automation/test-rhel.sh, automation/test.sh
=> replace variables

automation/test-rhel.sh
=> add namespace to local template name command

automation/test.sh
=> add oc project kubevirt command

automation/test.sh
=> fix kubevirt version

automation/test-rhel.sh
=> increase vm timeout

automation/test-rhel.sh
=> move debug lines

create-minikube-pvc.sh
=> disable dynamic provisioning in pvc

create-minikube-pvc.sh
=> add storageClassName

automation/test.sh, builder/Dockerfile
=> move image folder

builder/Dockerfile
=> add expect to dockerfile

automation/test-rhel.sh
=> replace expect script with virtctl console command

builder/Dockerfile
=> remove expect package

automation/test-rhel.sh
=> increase timeout for starting vm

.gitignore, generate-templates.yaml, templates/_linux.yaml
Signed-off-by: Vatsal Parekh <vparekh@redhat.com>
Fixes #187 
```release-note
Add a parameter for randomized password
```
=> Add a parameter for randomized password

automation/test-rhel.sh
=> added check which controls if vmi is deleted

automation/test.sh
=> increase kubevirt version

automation/test.sh
=> fix virtctl link

automation/test-rhel.sh
=> fix virtctl command

automation/test-rhel.sh, builder/Dockerfile
=> replaces virtctl console command with expect script

automation/test-rhel.sh
=> add sleep command to rhel test

automation/test.sh
=> set older kubevirt version

automation/test.sh, templates/_linux.yaml
=> set autoattachPodInterface to false

automation/test.sh, templates/_linux.yaml
=> switch to slirp interface

generate-templates.yaml
=> increase number of fedora cores

automation/test.sh
=> move creating of kubevirt config map

templates/_linux.yaml
=> change slirp to masquarade

automation/test-rhel.sh, automation/test.sh
=> switch from PVC to container image in tests

automation/ssp-operator-deploy/kubevirt-ssp-operator-cr.yaml, automation/ssp-operator-deploy/kubevirt-ssp-operator-crd.yaml, automation/ssp-operator-deploy/kubevirt-ssp-operator.yaml, automation/test-rhel.sh, automation/test.sh
=> added ssp operator which deploys template validator

automation/test-linux.sh
=> fix wworkloads for OSes

automation/test-linux.sh
=> fix condition for centos 7 and 8

generate-templates.yaml, templates/_linux.yaml
Add the Major Release of an OS to every template
Fixes #
```release-note
None
```
=> Add the Major Release of an OS to every template

automation/test-linux.sh, automation/test.sh, templates/_linux.yaml
=> switch to data volume templates with container disk

automation/test-linux.sh
=> fix too small value in pvc storage request

automation/test-linux.sh, automation/test.sh, templates/_linux.yaml
=> added basic datavolume from which VMs will clone disk in tests

travis_ci/release-templates-ssp-operator.sh
Signed-off-by: Vatsal Parekh <vparekh@redhat.com>
Add sign-off to the release script
Fixes #238 
```release-note
Add sign-off to the release script
```
=> Add sign-off to the release script

builder/Dockerfile
=> add DEFAULT_LOCAL_TMP variable to dockerfile

builder/Dockerfile, templates/_linux.yaml
=> create ansible tmp folder in dockerfile

builder/Dockerfile
=> add oc binary into Dockerfile

automation/test.sh
=> update command which gets latest kubevirt version

automation/test.sh
=> fix wrong namespace in test

templates/_linux.yaml
Signed-off-by: Vatsal Parekh <vparekh@redhat.com>
Fix typo in the username description
Fixes #
```release-note
Fix typo in the username description
```
=> Fix typo in the username description

automation/connect_to_rhel_console.exp, automation/test-linux.sh, automation/test.sh
=> set namespace as variable

automation/test.sh
=> move command which switches the namespace

automation/test-linux.sh, automation/test.sh
=> fix delete command in test

automation/connect_to_rhel_console.exp
=> update regex in script which checks if vm is alive in test

automation/test-linux.sh
=> remove log command and replaced by while loop

automation/test-linux.sh
=> add support for rhel in test

automation/test-linux.sh
=> fix wrong url in test

.travis.yml, automation/test-windows.sh, generate-templates.yaml, templates/deprecated-windows.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml, travis_ci/test_duplicate_templates.sh
This PR generates additional Windows Server templates specific to Windows 2k12 R2, Windows 2k16 and Windows 2k19
Fixes #
```release-note
None
```
=> Generate additional Windows Server templates specific to Windows 2k12 R2, Windows 2k16 and Windows 2k19

automation/test.sh
=> update command which fetch cdi version

automation/test.sh
=> add CDI secret

automation/test-linux.sh
=> remove secretRef for non rhel oses

builder/Dockerfile
add dockerfile which will be used for openshift ci
```NONE
```
=> add dockerfile which will be used for openshift ci

.travis.yml, generate-templates.yaml, templates/_linux.yaml, templates/deprecated-windows.tpl.yaml, templates/win2k12r2-deprecated.tpl.yaml, templates/windows10.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml, travis_ci/test_defaults.sh
This label will allow the UI to offer a sensible default template for the selected operating system.
It effectively removes one VM creation step for users who don't have very specific requirements.
Fixes #
```release-note
NONE
```
=> Add a new template label to define a default variant for each OS

README.md
This PR brings on only cosmetic fixes, such as renaming "Cent OS" to "CentOS", and also having the CentOS 8 entry pointing to the correct template (centos8 one, instead of the centos7).
Fixes #
```release-note
NONE
```
=> README: Fix typos in the CentOS entries

generate-templates.yaml
Drop major verison from PVC names of community OSs in order to have a fixed PVC for upgrades and prevent confusion with a constantly updated description
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1897081
```release-note
NONE
```
=> Drop major verison from PVC names of community OSs

dvtemplates/Dockerfile, dvtemplates/fedora-datavolume-template.yaml, dvtemplates/fedora_new_image.sh
Add a script to check and download the latest fedora image 
Fixes #
```release-note
```
=> Add a script to check and download the latest fedora image

automation/test-linux.sh, automation/test_cdi.sh, automation/unit-tests.sh, automation/validate-pvc-name-stability.py, dvtemplates/Dockerfile, dvtemplates/fedora-datavolume-template.yaml, dvtemplates/fedora_new_image.sh, templates/centos6.tpl.yaml, templates/fedora.tpl.yaml, templates/rhel6.tpl.yaml
Fixes #
```release-note
None
```
=> Modify test script to support both k8s and openshift environment

templates/ubuntu.tpl.yaml
- Display name now pulled from osinfo
- Code name now pulled from osinfo
- URL now constructed from code name
Fixes #316 
```release-note
NONE
```
=> Fixed hard-coded values in Ubuntu template

automation/test-windows.sh, generate-templates.yaml, templates/windows10.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml
This PR adds high performance templates for Windows. This is a work in progress since changes must be done to the template files themselves.
```release-note
NONE
```
=> Add Windows high performance templates

automation/test-linux.sh, automation/test-windows.sh, automation/test.sh, generate-templates.yaml, templates/fedora.tpl.yaml, templates/rhel7.tpl.yaml, templates/rhel8.tpl.yaml, templates/ubuntu.tpl.yaml, templates/windows10.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml
=> Fedora CDI creation

automation/test-linux.sh
=> Remove "Contenttype" Fix for CDI Issue

automation/unit-tests.sh
Add missing test_id.
```release-note
NONE
```
=> add test_id for pvc stability test

dvtemplates/fedora_new_image.sh
=> Modify script to change docker registry

automation/test-linux.sh, automation/test.sh, dvtemplates/fedora_new_image.sh
=> Revert back to using oc client

dvtemplates/fedora_new_image.sh
Use the Fedora Release url - https://getfedora.org/releases.json to identify the latest releases, and their image download links
```release-note
None
```
=> Use the Fedora Release url - https://getfedora.org/releases.json to identify the latest releases, and their image download links.

dvtemplates/build_k8s_cluster.sh, dvtemplates/new_cdi_image.sh
Modify script to support both CentOS and Fedora periodic job
=> Modify script to support both CentOS and Fedora periodic job

automation/test.sh, dvtemplates/build_k8s_cluster.sh, dvtemplates/new_cdi_image.sh
Enable CPUmanager
```release-note
None
```
=> Enable CPUmanager

templates/windows10.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml
add support for stimer direct to windows templates
/hold
```
add support for stimer direct to windows templates
```
=> add support for stimer direct to windows templates

automation/test-linux.sh, automation/test-windows.sh, dvtemplates/new_cdi_image.sh
1. Updated the Fedora quay repo
2. Added an additional latest tag to the image uploadd to the final repo
3. Cleanup during the test run to make resources available
Fixes #
```release-note
None
```
=> Minor additions and modifications to the Fedora and CentOS Periodic Jobs

builder/Dockerfile, generate-templates.yaml, templates/rhel9.tpl.yaml
add new rhel 9 template
Fixes #
```
add RHEL 9 template
```
=> Add new rhel 9 template

builder/Dockerfile
Add golang to the builder container for the tests needed for https://github.com/openshift/release/pull/21019/
```release-note
NONE
```
=> Add golang to the builder container for the tests

templates/rhel9.tpl.yaml
update rhel 9 template description
```
Updated RHEL9 template description
```
/cc @akrejcir @kwiesmueller
=> update rhel 9 template description

templates/centos6.tpl.yaml, templates/centos7.tpl.yaml, templates/centos8.tpl.yaml, templates/fedora.tpl.yaml, templates/opensuse.tpl.yaml, templates/rhel6.tpl.yaml, templates/rhel7.tpl.yaml, templates/rhel8.tpl.yaml, templates/rhel9.tpl.yaml, templates/ubuntu.tpl.yaml, templates/windows10.tpl.yaml, templates/windows2k12.tpl.yaml, templates/windows2k16.tpl.yaml, templates/windows2k19.tpl.yaml
change datavolume api version to v1
```
change datavolume api to v1 in all templates
```
=> change datavolume api version to v1

OWNERS
update owners file to reflect current contributors
```
NONE
```
=> update owners file to reflect current contributors

.github/workflows/release.yaml
Change user fork in github actions
```
NONE
```
=> Change user fork in github actions

generate-templates.yaml
remove generation of sap hana template
We don't want to ship sap hana template in current release
```
Remove sap hana template
```
=> remove generation of sap hana template

generate-templates.yaml
Added 'when: 0 > 1' to the ansible task.
```release-note
None
```
=> Add a condition to saphana ansible task to disable it

templates/rhel8.saphana.tpl.yaml
The UI will let users fill in the required parameters for SAP HANA template
https://issues.redhat.com/browse/CNV-14867
The UI will use the `displayName` field to correctly display titles for the parameter inputs
https://issues.redhat.com/browse/CNV-14867
UI pull request to use this fields: https://github.com/openshift/console/pull/10617
```release-note
Add displayName field to correctly display titles for the parameter inputs for SAP HANA template in the UI
```
=> Add displayName for SAP HANA template parameters

generate-templates.yaml
Signed-off-by: Dominik Holler <dholler@redhat.com>
```release-note
- Enable the generation of the rhel8.saphana
```
=> Enable the generation of the rhel8.saphana

automation/test-linux.sh, generate-templates.yaml, templates/centos-stream8.tpl.yaml, templates/centos-stream9.tpl.yaml
add centos stream 8 and 9 templates 
update osinfo
delete centos 8 template because centos 8 is EOL
```
Drop centos 8 template because centos 8 is EOL
Add centos stream 8 and 9
```
=> Centos stream

generate-templates.yaml, templates/opensuse.tpl.yaml
- Correct spelling of openSUSE
- Automatically load active openSUSE versions
```release-note
Include support for latest and active openSUSE versions
```
=> Improve openSUSE template

automation/test-linux.sh, generate-templates.yaml, templates/ubuntu.tpl.yaml
- Add server workload to template and make it the default
- Remove unnecessary tiny flavor
- Automatically load active Ubuntu versions
```release-note
Added Ubuntu server workload as new default
Removed Ubuntu tiny flavor
Include support for latest and active Ubuntu versions
```
=> Improve Ubuntu template

builder/Dockerfile
Cleanup `builder/Dockerfile` and prepare it for containerdisk annotations test. (#417)
- Use quay.io/fedora/fedora:latest as base
- Remove unused dependencies / tools
- Cleanup syntax
- Download latest oc client binary
- Add latest yq binary (needed for containerdisk annotations test)
- Add comments
```release-note
None
```
=> Cleanup builder/Dockerfile

automation/test_defaults.sh, automation/test_duplicate_templates.sh
Improve the existing unit tests in `automation/test_defaults.sh` and
`automation/test_duplicate_templates.sh` by using `yq` instead of grepping
yaml files.
Merge after #418
```release-note
None
```
=> Improve existing unit tests

automation/test_containerdisk_annotations.sh, automation/unit-tests.sh
This adds a test for the appropriate templates which ensures that the
actual templates in a live cluster contain the containerdisk
annotations.
Merge after #418
```release-note
None
```
=> Add containerdisk annotations test

automation/test-linux.sh, automation/test_containerdisk_annotations.sh, automation/unit-tests.sh, templates/LABELS.md
remove automation for sap hana template
sap hana template was migrated to https://github.com/RHsyseng/cnv-supplemental-templates/blob/main/templates/saphana/rhel8.saphana.yaml
```NONE
```
=> remove automation for sap hana template

templates/rhel9.tpl.yaml
Signed-off-by: prnaraya <prnaraya@redhat.com>
Fixes #
```release-note
Removing "Beta" from RHEL 9 template name and recommended url
```
=> Updating RHEL 9 Template name and recommended url

README.md, automation/test-windows.sh, generate-templates.yaml, templates/windows2k22.tpl.yaml
Add Windows server 2022 template
Fixes #
```release-note
Add Windows server 2022 template
```
=> Add windows2022 template

OWNERS
Add fossedihelm to reviewer list
Fixes #
```release-note
NONE
```
/cc @0xFelix
=> Add fossedihelm to reviewer list

.github/workflows/release.yaml
This PR updates SSP master to main.
```
None
```
=> feat: Change ssp master to main

.github/workflows/release.yaml
This PR reverts change of SSP branch name.
```
None
```
=> feat: Revert change of ssp branch name

.github/workflows/release.yaml
This PR renames ssp master branch to main.
```
None
```
=> feat: Rename ssp master branch to main

templates/fedora.tpl.yaml
Fixes #
```release-note
NONE
```
=> fix: disable SMM on Fedora for s390x architecture

generate-templates.yaml, templates/ubuntu.tpl.yaml
Fixes #
```release-note
NONE
```
=> feat: s390x Ubuntu enablement

makefile
Re-add the missing generate target to the dist/common-templates.yaml target.
Fixes #
```release-note
None
```
=> fix(makefile): Re-add missing generate target

automation/unit-tests.sh
bundle name now contains the version
Fixes #
```release-note
NONE
```
=> fix(unit test): pick the right common-templates

.github/workflows/release.yaml, generate-templates.yaml, makefile, templates/centos-stream9.tpl.yaml, templates/fedora.tpl.yaml, templates/rhel9.tpl.yaml, templates/ubuntu.tpl.yaml
Enables arm64 support for common templates
Fixes #
```release-note
arm64 support
```
=> Enable arm64 builds

makefile
Include arm64 generated file.
Fixes #
```release-note
none
```
/cc @ksimon1 @0xFelix
=> Fix release process
